# Generated by Django 2.1.3 on 2018-11-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('netbiosname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('macadress', models.GenericIPAddressField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('formfactor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servermodelname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='servermodel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serversapp.ServerModel'),
        ),
    ]
